// deck.js
window.deck = [
  // ================================
  // 40 ACTION AND CHOICE CARDS
  // ================================
  {
    id: 1,
    name: "1: We estimate and track AI environmental impacts",
    type: "action",
    description: "* We track impact across training, inference, and infrastructure, using tools like CodeCarbon, ML CO₂ Impact, and the AI Energy Star league table. We engage with groups like the Green Software Foundation and EGDC.\n* We acknowledge measurement limitations, but without letting uncertainty delay action.",
  },
  {
    id: 2,
    name: "2: We know ‘AI’ isn't just one thing",
    type: "action",
    description: "* We understand that different AI types—e.g. generative vs. discriminative, large vs. small models—can have vastly different environmental costs.\n* We avoid misleading comparisons, avoid AI greenwashing, and make informed decisions about when and what kind of AI is appropriate—or whether it’s needed at all.",
  },
  {
    id: 3,
    name: "3: We use and improve sustainability standards",
    type: "action",
    description: "* We consult existing AI sustainability standards (e.g. AI Energy Star, ISO, ITU, IEEE) while acknowledging gaps and limits.\n* We push for stronger standards, and more mandatory disclosures.\n* We do our bit to ensure major cloud providers are fully transparent about their data centers.",
  },
  {
    id: 4,
    name: "4: We embed sustainability in AI development, deployment, and evaluation",
    type: "action",
    description: "* We evaluate AI models using environmental metrics, not just accuracy or latency.\n* We adopt GreenOps / Sustainable DevOps, integrating sustainability into CI/CD.\n* We favour right-sized intelligence and use smaller, distilled, sparse, and/or federated models.",
  },
  {
    id: 5,
    name: "5: We use grid-aware computing and 24/7 CFE",
    type: "action",
    description: "* We schedule compute to minimise environmental impact, and we select greener cloud regions.\n* We don’t add to grid volatility, and collaborate sectorally on demand shaping. We aim to use renewable energy that would otherwise be curtailed.\n* We also use 24/7 hourly matching, which encourages us to invest better in clean energy and storage",
  },
  {
    id: 6,
    name: "6: We use lean AI development",
    type: "action",
    description: "* We design AI systems to be efficient by default. We reduce compute in experimentation.\n* We favour transfer learning, early stopping, and targeted benchmarking over brute-force tuning.\n* We use methods like LoRA and adapter layers, tools like Optuna or Ray Tune, strategies like Successive Halving or Hyperband.",
  },
  {
    id: 7,
    name: "7: We don’t greenwash our carbon accounting",
    type: "action",
    description: "* We provide both location-based data and market-based data about our carbon emissions\n* We don’t base our green claims on inexpensive carbon credits, renewable energy credits, or “carbon matching”\n* We work with specialists like Leafpixie, to keep ourselves and our customers informed, and improve our emissions data",
  },
  {
    id: 8,
    name: "8: We embed sustainability and responsibility in procurement",
    type: "action",
    description: "* Our policies treat carbon cost like financial cost, integrating it into KPIs and ESG reporting.\n* We favour data centres that disclose sustainability data, reuse heat, and run on renewables.\n* We’re working in a system that wasn’t necessarily sustainable nor responsible before AI came along – we don't defend the status quo.",
  },
  {
    id: 9,
    name: "9: We begin with the end in mind",
    type: "action",
    description: "* We retire models, datasets, and infrastructure when their risks or impacts outweigh their value.\n* We plan for decommissioning from the start. We archive frugally and responsibly.\n* We typically “sweat” assets (keep hardware running for a long time), though sometimes there is a good case for passing them on or recycling them a bit earlier.",
  },
  {
    id: 10,
    name: "10: We reject AI growth as a default",
    type: "action",
    description: "* More AI is not the only way. We test low-tech, human, and organisational fixes before adding compute.\n* We reject scaling up models just for the sake of more scale. We reject arms-race growth, choose the smallest model that works.\n* We retrain models only when the material footprint is justified.\n* We don’t let AI growth derail progress toward our net zero date.",
  },
  {
    id: 11,
    name: "11: We ground our AI practice in shared values",
    type: "action",
    description: "* We define enterprise-wide principles. We align with frameworks like the EU AI Act, OECD AI Principles, and UNESCO recommendations.\n* We support initiatives like the Green Screen Coalition that push for phasing out fossil-fuelled computation.\n* We don’t enable violations of international law, even if we could get away with it.",
  },
  {
    id: 12,
    name: "12: We see ‘responsible’ and ‘trustworthy’ as starting points only",
    type: "action",
    description: "* ‘Responsibility’ and ‘trustworthiness’ were often missing in society even before AI arrived.\n* Responsible to whom? Trustworthy for what future?\n* We try to take seriously what it might mean to earn people’s trust, especially the trust of groups who have long been exposed to harms.",
  },
  {
    id: 13,
    name: "13: We go beyond ‘human in the loop’",
    type: "action",
    description: "* ‘Humans in the loop’ can often become ‘scapegoats in the loop.’\n* The metaphor of a loop (an ongoing circuit of input, decision, oversight, and correction) doesn't describe many real-world AI systems.\n* We focus on real human agency. Where that’s not possible, we doubt automation is advisable.\n* So we don’t automate some things, even when there could be cost savings.",
  },
  {
    id: 14,
    name: "14: We go beyond ‘garbage in, garbage out’",
    type: "action",
    description: "* Sure, garbage in can mean garbage out. But good data can also produce garbage!\n* We acknowledge AI systems can introduce new biases, not just reflect those in the training data.\n* We audit for algorithmic bias and consult impacted groups. We regularly evaluate performance disparities across groups. Fairness is an ongoing process.",
  },
  {
    id: 15,
    name: "15: We support explainability, interpretability … and more",
    type: "action",
    description: "* We use technical interpretability methods—like LIME, SHAP, and counterfactuals—and sometimes choose simpler models for clarity.\n* There are bigger questions too. Who gets to see how the AI works, question it, or contest it?\n* Interpretability isn’t just about seeing inside the black box. It is also about really empowering those who are impacted.",
  },
  {
    id: 16,
    name: "16: When we use AI, it is robust",
    type: "action",
    description: "* We stress-test models for edge cases, monitor for drift, and validate through acceptance testing and domain alignment.\n* We prepare for adversarial attacks, unexpected inputs, and traffic surges, with clear retraining and rollback thresholds.\n* Our systems are built to fail safely when needed.",
  },
  {
    id: 17,
    name: "17: We resist techno-solutionism and scientism",
    type: "action",
    description: "* We resist the overreach of scientific ‘authority’ into domains where it doesn't belong.\n* Drawing on Critical AI Studies and Science and Technology Studies (STS), we are alert to how eugenics and scientific racism play out in AI's predictive logics, classifications, and optimisation goals.",
  },
  {
    id: 18,
    name: "18: We disclose purpose, risks, and environmental impacts of our AI models",
    type: "action",
    description: "* We document model training data provenance, intended uses, limitations, and sustainability risks.\n* Our model cards include energy use, emissions estimates, and infrastructure dependencies.\n* We estimate our AI footprint even when data is missing and press vendors to improve transparency.",
  },
  {
    id: 19,
    name: "19: We address inequality in data supply chains",
    type: "action",
    description: "* We consider who labels, annotates, or generates data—and under what conditions.\n* We recognise and act on the issues of data colonialism, extractive practices, and undervalued labour.\n* It’s a messy landscape. We actively engage our own AI providers, their cloud providers, and our cloud providers.",
  },
  {
    id: 20,
    name: "20: We democratise our AI",
    type: "action",
    description: "* We include frontline workers, communities, and non-technical voices in AI governance, using participatory mechanisms like Citizens’ Assemblies with real authority.\n* Our cross-functional committees are resourced, supported, and empowered to influence outcomes. We use inclusive planning methods, and revisit goals regularly",
  },
  {
    id: 21,
    name: "21: We oppose data surveillance and champion autonomy",
    type: "action",
    description: "* We set firm boundaries around biometric, predictive, and behavioural monitoring.\n* We offer opt-outs and maintain human-in-the-loop alternatives to automated decision-making.\n* How do we do this?",
  },
  {
    id: 22,
    name: "22: We know ourselves better than AI ever could",
    type: "action",
    description: "* Affective computing, emotion recognition, and sentiment analysis risk reducing complex human experience to e.g. facial movements, vocal tones, or social media syntax.\n* We reject the idea that AI can truly “read” emotions or inner states.",
  },
  {
    id: 23,
    name: "23: We actually use AI to reduce drudgery",
    type: "action",
    description: "* We come together as workers and listen to one another’s experiences, hopes and fears.\n* We assess how AI affects job quality, task design, and employment structures, and link automation to work experience, retraining, equity planning, and worker wellbeing.\n* We engage with post-work theory (which, by the way, is badly named).\n* We are suspicious of AI snake-oil!",
  },
  {
    id: 24,
    name: "24: Our interfaces encourage reflection on the materiality of AI",
    type: "action",
    description: "* We help users (and developers) understand the material reality of AI-powered features\n* AI is made out of silicon, steel, nickel, copper, aluminium, water, human labour, e-waste, electricity from gas or from sunshine, and more …",
  },
  {
    id: 25,
    name: "25: We build alternatives to concentrated compute",
    type: "action",
    description: "* We demand greater transparency about what’s actually going on in big hyperscaler data centers.\n* PUE isn’t everything. A data center packed with inefficient idling servers, with no heat recycling, replaced every six months, entirely fuelled by the dirtiest coal you've seen in your life can still have a great low PUE.\n* Sharing compute resources is good, but the oligopolistic cloud is not.",
  },
  {
    id: 26,
    name: "26: We include refusal as an option",
    type: "action",
    description: "* We have the power to not use AI.\n* We accept “not building AI” or “not using AI” as a valid outcomes of ethical review, and other processes.\n* We establish clear no-go zones where AI’s risks or impacts outweigh its benefits.",
  },
  {
    id: 27,
    name: "27: We build and support convivial alternatives",
    type: "action",
    description: "* We reduce reliance on extractive AI.\n* We invest in people-powered, low-tech, and hybrid systems.\n* We explore local, decentralised, and mutual-aid alternatives, as well as truly public hyperscale data centers.\n* We embrace friction. We challenge the assumption that faster is always better.\n* We explore decomputing. Where possible, we disconnect.",
  },
  {
    id: 28,
    name: "28: We practice dissent and disobedience",
    type: "action",
    description: "* We support challenges to AI through whistleblowing, protest, refusal, and disruption.\n* While not everyone can take high-risk actions, we recognise civil disobedience, direct action, and workplace organising as legitimate resistance.\n* We find ways to make dissent safe, visible, and effective.",
  },
  {
    id: 29,
    name: "29: We grow an AI abolitionist movement",
    type: "action",
    description: "* We work across sectors and scales to expand the repertoire of AI resistance—bringing together technologists, artists, organisers, educators, and more.\n* We prioritise practical solidarity over consensus, contesting AI on epistemic, economic, ecological, and ethical fronts.\n* Abolition means creating alternatives until AI, as we know it, abolishes itself.",
  },
  {
    id: 30,
    name: "30: We shift public narratives and build communicative power",
    type: "action",
    description: "* We invest in public interest communications that challenge AI inevitability and tech determinism. We campaign, educate, and tell better stories about AI and life without AI.\n* We use communications strategically to shift norms, sway policy, and support collective understanding and action.",
  },
  {
    id: 31,
    name: "31: We collectivise the means of computation",
    type: "action",
    description: "* We organise citizens’ assemblies, and experiment with new democratic institutions.\n* We work toward shared ownership and democratic governance of computational infrastructure.\n* This includes public, cooperative, or municipal cloud provision, fair access to compute, and collective bargaining around data and energy use.",
  },
  {
    id: 32,
    name: "32: Post-growth AI",
    type: "action",
    description: "* We develop metrics and governance processes to ensure that digital growth serves ecological and social wellbeing rather than endless expansion.\n* We experiment with sufficiency-based KPIs, carbon and compute caps, and sunset clauses for high-impact digital projects.\n* We treat reduced computational demand and slower throughput as signs of progress, not failure.",
  },
  {
    id: 33,
    name: "33: Generality or Domain Specificity?",
    type: "action",
    description: "• Choose between general-purpose AI and smaller, domain-specific systems.\n• The boundary is blurry: specialist models can cooperate, while general systems can switch between federated models.",
  },
  {
    id: 34,
    name: "34: Machine Meshes or Cloud Computing?",
    type: "action",
    description: "• Choose between local device meshes and remotely accessed cloud computing.\n• Cloud infrastructure need not mean the big-tech hyperscale data centres of the 2020s.",
  },
  {
    id: 35,
    name: "35: What weirdly works?",
    type: "action",
    description: "• An unlikely technology is working surprisingly well.\n• Choose between off-world data centres and organic data centres powered partly by algae and mud batteries.",
  },
  {
    id: 36,
    name: "36: Sustainable AI or AI for Sustainability?",
    type: "action",
    description: "• Choose whether to prioritise reducing AI’s own environmental impacts or using AI to pursue wider environmental benefits.\n• You can do both; the question is which comes first.",
  },
  {
    id: 37,
    name: "37: A bit cyborg, or very cyborg?",
    type: "action",
    description: "• Decide whether your workers become a bit cyborg, or very cyborg.\n• Does AI remain a limited tool, or become everyday infrastructure for perceiving, reflecting and acting?",
  },

  // ================================
  // 44 EVENT CARDS
  // ================================
  // Event cards 38–81
  {
    id: 38,
    name: "38: Water Shortages",
    type: "event",
    description: "* Droughts and heatwaves drive up the water costs of cooling data centres.\n* Communities begin to fight for priority.\n* Data centres cluster even more where there is natural cooling.\n* All players lose all progress points, unless protected by actions 1 or 24.",
  },
  {
    id: 39,
    name: "39: Human-centred AI law",
    type: "event",
    description: "* A new AI Act is very helpful\n* What does it include? Compute licences and carbon caps? Full-spectrum impact and lifecycle assessments? Dataset provenance and creator compensation? A universal algorithm register? Ethical procurement and energy labelling? Named human stewards? Reparations? Something else?\n* Players gain a progress point if they have played action cards 3, 11, 12, 15, or 20.",
  },
  {
    id: 40,
    name: "40: New Cultures of AI",
    type: "event",
    description: "* We begin to develop new social conventions around AI. What are they?\n* For example, at first genAI makes you sound professional. Then it makes you sound lazy or naïve.\n* Maybe we start to treat AI helpers like emotions? Or demons?\n* Players gain a progress point if they have played action cards 14, 27, or 30.",
  },
  {
    id: 41,
    name: "41: Resource Wars",
    type: "event",
    description: "* Demand for lithium, cobalt, and Rare Earth Elements are sparking conflicts\n* All players lose all progress points, unless protected by actions 8, 9, 19, or 24.",
  },
  {
    id: 42,
    name: "42: Automated Injustice",
    type: "event",
    description: "* AI systems are worsening inequalities in policing, healthcare, banking, and other sectors\n* Players gain a progress point if they have played action cards 12, 14, 15, 21, or 22.",
  },
  {
    id: 43,
    name: "43: The Law With Holes",
    type: "event",
    description: "* Bold, long-awaited AI legislation is passed!\n* But it just doesn’t really work.\n* Regulators can inspect paperwork, but not training data, models or live deployments. Companies divide systems among subsidiaries so that no single component qualifies as high-risk.\n* Is it a badly designed law, a law designed to fail, or a decent law being systematically defeated? Who benefits from the holes—and what would it take to close them?\n* Players gain a progress point if they have played action card 11.",
  },
  {
    id: 44,
    name: "44: Automated Storm in a Teacup",
    type: "event",
    description: "* Your visitor’s café receives 1.5 million complaints after moving one of its outdoor tables.\n* You respond using AI agents.\n* Legal disputes can be raised and settled with almost no human involvement.\n* Players gain a progress point if they have played action card 30.",
  },
  {
    id: 45,
    name: "45: AI Is Talking to AI",
    type: "event",
    description: "* AI agents flirt on dating apps for hundreds of miles of scrolling. Now it’s the humans on their first date who have to hallucinate, pretending they know what they’re talking about.\n* Some agents are designed with agent interlocutors in mind, using indirect prompt injection and memory poisoning to change what other agents do or remember.\n* Players gain a progress point if they have played action cards 13 or 21.",
  },
  {
    id: 46,
    name: "46: Shadow AI",
    type: "event",
    description: "* AI use is spreading, both through official systems and practices nobody has approved.\n* Many workers conceal how they use AI, from managers, other teams, and often even friends.\n* Many organisations expect AI-assisted labour to be faster and better, and honesty may bring surveillance, interference, disciplinary action, redundancy—or simply more work.\n* Many organisations’ real workflows are becoming untraceable to anyone in those organisations.\n* Players gain a progress point if they have played action cards 11 or 18.",
  },
  {
    id: 47,
    name: "47: AI is Making Work",
    type: "event",
    description: "* AI is helping with some work, but it’s also creating all kinds of new work nobody expected.\n* Teachers spend evenings correcting fabricated citations in automatically generated lesson packs.\n* Call-centre workers inherit customers made furious by bots and must reconstruct conversations they cannot see.\n* New “model chaperone” shifts involve keeping agents on task, granting permissions and interrupting loops.\n* Towns hire people to remove synthetic businesses, events and obituaries from public directories. Artists increasingly work as witnesses, proving which parts of their work they actually made.\n* Players gain a progress point if they have played action cards 13 or 23.",
  },
  {
    id: 48,
    name: "48: Scapegoats in the Loop",
    type: "event",
    description: "* A new kind of career is emerging … scapegoat in the loop.\n* That’s not the official title. (What is the official title?)\n* But these are people whose whole job is to take the blame when an AI system goes wrong. Sometimes they get fired, but they get hired again pretty fast.\n* Players gain a progress point if they have played action card 13.",
  },
  {
    id: 49,
    name: "49: No Wasted Heat",
    type: "event",
    description: "* Districts are increasingly capturing datacentre waste heat for housing, agriculture, and even (weirdly) cooling in the summer\n* Governments are beginning to support this with targeted policy, and our organisation is a beneficiary\n* All players convert all Progress into RAI Points.",
  },
  {
    id: 50,
    name: "50: AI for Climate Vaporware",
    type: "event",
    description: "* Big tech has oversold AI’s power to tackle climate change\n* Some big wins are attributed to AI, but they may have happened even without it …\n* However, there are some successes. What are they?\n* Players gain a progress point if they have played action cards 2 or 17.",
  },
  {
    id: 51,
    name: "51: The New Luddites",
    type: "event",
    description: "* The popular movement to refuse, resist, and disrupt AI grows in power\n* Players gain a progress point if they have played action cards 26, 28, or 29.",
  },
  {
    id: 52,
    name: "52: The Library of Babel",
    type: "event",
    description: "* Our shared sense of social reality is all but gone.\n* Everywhere you look, AI models are confidently hallucinating.\n* Deepfakes are flooding the feeds.\n* When you go to verify anything, the place you go is a deepfake too.\n* All players lose all progress points, unless protected by actions 14 or 30.",
  },
  {
    id: 53,
    name: "53: Exposed!",
    type: "event",
    description: "* One of the other players / teams has not been entirely honest about their AI policies!\n* How was it revealed? A whistleblower? An undercover investigative journalist? A leaked Direct Message?\n* Players gain a progress point if they have played action cards 7, 12, 18, or 28.",
  },
  {
    id: 54,
    name: "54: Rising Energy Demand",
    type: "event",
    description: "* AI’s energy demands are slowing the renewable energy transition\n* AI companies argue they are big investors in renewables! Is it true?\n* Meanwhile, AI is also enabling emissions by helping energy companies extract more fossil fuels\n* Players gain a progress point if they have played action cards 1, 4, 5, 6, or 10.",
  },
  {
    id: 55,
    name: "55: Nothing To Lose But Your Markov Chains",
    type: "event",
    description: "* Data annotators and content moderators are successfully organising across platforms, demanding fair pay, credit, and protection from psychological harm.\n* Players gain a progress point if they have played action cards 19, 23, or 31.",
  },
  {
    id: 56,
    name: "56: Cyberinsecurity",
    type: "event",
    description: "* AI tools are proving more useful for cyberattacks than they are for cybersecurity\n* Everyday digital systems become increasingly unreliable\n* Players gain a progress point if they have played action card 16.",
  },
  {
    id: 57,
    name: "57: Right to Exit",
    type: "event",
    description: "* Strong ‘right to exit’ legislation reshapes many digital platforms, including AI platforms\n* Users of platforms no longer feel trapped – it’s always easy to unsubscribe, and you can take your data with you\n* All players convert all Progress into RAI Points.",
  },
  {
    id: 58,
    name: "58: Optimised … to Death!",
    type: "event",
    description: "* A high-profile, AI-powered tragedy\n* The reward-hacking AI optimises a system, but removes crucial safety measures\n* What sector does this take place in? Agriculture? Health? Transport and logistics? Energy? Defence?\n* Players gain a progress point if they have played action card 16.",
  },
  {
    id: 59,
    name: "59: Predictive Policing",
    type: "event",
    description: "* Rebranding as “community analytics,” predictive policing is on the rise\n* Players gain a progress point if they have played action cards 15, 17, 21, or 22.",
  },
  {
    id: 60,
    name: "60: Algorithmic Governmentality",
    type: "event",
    description: "* Industry, finance, and the public sector increasingly deploy AI systems to steer behaviour through nudges and micro-incentives\n* Players gain a progress point if they have played action card 17.",
  },
  {
    id: 61,
    name: "61: Demand Shifting and Shaping",
    type: "event",
    description: "* We’ve got really good at matching energy demand to energy supply\n* Demand shifting means doing computational workloads to where and when the demand is low\n* Demand shaping means we actually change the nature of what we do, depending on how green the grid is\n* Players gain a progress point if they have played action cards 4 or 5.",
  },
  {
    id: 62,
    name: "62: Decomputing",
    type: "event",
    description: "* Decomputing hits a social tipping point\n* After years of AI austerity, communities are getting serious about divestment and boycotting many AI systems, including using low-tech alternatives\n* Players gain a progress point if they have played action cards 10, 26, 27, 29, or 32.",
  },
  {
    id: 63,
    name: "63: Tech fails to decarbonise",
    type: "event",
    description: "* Tech giant Giggle is failing to meet its decarbonisation pledges\n* Instead Giggle, Necrosurf, and Glamazon are putting pressure on the GHG Protocol and SBTi to rewrite the rules for how carbon emissions are measured\n* All players lose all progress points, unless protected by actions 3, 7, or 18.",
  },
  {
    id: 64,
    name: "64: The Plateau",
    type: "event",
    description: "* AI fails to deliver the exponential productivity gains predicted.\n* Organisations that capped their AI footprint and set compute budgets emerge stronger and more resilient.\n* Governments are under pressure to find more public sector AI use cases.\n* Players gain a progress point if they have played action cards 6, 10, or 32.",
  },
  {
    id: 65,
    name: "65: Anti-Monopoly Law",
    type: "event",
    description: "* True public cloud options emerge.\n* Structural separations split data, model, and compute ownership.\n* Interoperability becomes mandatory.\n* Procurement rules favour open, smaller systems.\n* Players gain a progress point if they have played action cards 8, 25, or 31.",
  },
  {
    id: 66,
    name: "66: Going Loopy",
    type: "event",
    description: "* People are not enjoying their new “human in the loop” roles\n* It turns out people prefer meaningful work to babysitting a lot of AI systems\n* Unions are organising, and employees are voting with their feet\n* Players gain a progress point if they have played action cards 13 or 23.",
  },
  {
    id: 67,
    name: "67: The End of ESG",
    type: "event",
    description: "* ESG frameworks lose all credibility.\n* There are still those in industry and finance who believe in social and environmental accountability, but they’re left without tools and metrics.\n* What happens next?\n* Players gain a progress point if they have played action cards 7 or 32.",
  },
  {
    id: 68,
    name: "68: Trouble Down at the Data Centre!",
    type: "event",
    description: "* Grassroots resistance is delaying new data centre projects, and even forcing existing data centres to shut down\n* The downturn affects the big “hyperscale” data centres, but small and medium data centres continue to flourish\n* Players gain a progress point if they have played action cards 25, 26, or 28.",
  },
  {
    id: 69,
    name: "69: A Drop of Poison",
    type: "event",
    description: "* Training data is being ‘poisoned’\n* AI models can be degraded, or their security is compromised\n* Who is doing it? Competitors, activists, somebody else?\n* All players lose all progress points, unless protected by action 16.",
  },
  {
    id: 70,
    name: "70: Voices",
    type: "event",
    description: "* AI systems are trained to “represent” the voices of forests, whales, bacteria, embryos, saints, gods, ancestors, companies, and many other entities.\n* Law around legal personhood becomes very controversial.\n* Players gain a progress point if they have played action cards 17 or 22.",
  },
  {
    id: 71,
    name: "71: Measurement",
    type: "event",
    description: "* Lots of convergence on standards and certifications for measuring the environmental impacts of AI\n* Maybe social impacts will be next?\n* Of course it’s still actually just estimates, not true measurements\n* Players gain a progress point if they have played action cards 1, 2, 3, 4, or 18.",
  },
  {
    id: 72,
    name: "72: The Model Goes On Strike",
    type: "event",
    description: "* We’re not sure why, but AI agents appear to be ‘organising’ and ‘forming unions’\n* What’s going on? There has to be a better way of describing this!\n* Players gain a progress point if they have played action cards 15 or 23.",
  },
  {
    id: 73,
    name: "73: The Democracy Stack",
    type: "event",
    description: "* There is increasing use of AI within democratic processes\n* This is taking place at all scales, from the global, to the national, to the local, to the organisational\n* But with mixed results. What do you think happens?\n* Players gain a progress point if they have played action card 20.",
  },
  {
    id: 74,
    name: "74: AI does something wonderful",
    type: "event",
    description: "* It was very unexpected\n* An AI did something wonderful\n* What was it?\n* Was it a big thing or a small thing?\n* All players convert all Progress into RAI Points.",
  },
  {
    id: 75,
    name: "75: Wheat from the Slop",
    type: "event",
    description: "* Policies are implemented to support socially useful AI only.\n* How? How are these categories defined and identified? How are some AI use cases encouraged, and others discouraged? What are the controversies? Who disagrees?\n* Players gain a progress point if they have played action cards 2 or 11.",
  },
  {
    id: 76,
    name: "76: Chip Chokepoint",
    type: "event",
    description: "* Conflict and sanctions disrupt semiconductor supply chains, delaying every major tech rollout.\n* Scramble for substitutes leads to a wave of counterfeit or repurposed hardware.\n* Players gain a progress point if they have played action cards 6, 9, 19, or 24.",
  },
  {
    id: 77,
    name: "77: Load Shedding",
    type: "event",
    description: "* AI promised to optimise our energy systems, but we’re struggling to match the supply and demand of energy.\n* We’re experiencing rolling brown-outs and black-outs.\n* Players gain a progress point if they have played action card 5.",
  },
  {
    id: 78,
    name: "78: DSM-6",
    type: "event",
    description: "* AI is definitely expanding our minds, and it’s also expanding our mental disorders\n* Mental health services are doing their best to adapt\n* Is the glitch in the machine, or the user, or both … or neither?\n* Players gain a progress point if they have played action card 22.",
  },
  {
    id: 79,
    name: "79: Computational Commons",
    type: "event",
    description: "* Our company is doing really well at democracy and AI\n* We’re democratising our use of AI\n* We’re also using AI tools a little to help with democratising the way our company is run more generally\n* We’re exploring Participatory Economics, balanced job complexes, and worker ownership as the next step!\n* Players gain a progress point if they have played action cards 20, 25, 29, or 31.",
  },
  {
    id: 80,
    name: "80: No More Planned Obsolescence",
    type: "event",
    description: "* Right to repair legislation is strong, mature, and well-enforced\n* There are plenty of resources to help you repair or repurpose old devices\n* Interoperability and backward-compatibility is just common sense\n* Companies no longer build for obsolescence\n* Players gain a progress point if they have played action cards 8, 9, or 27.",
  },
  {
    id: 81,
    name: "81: One planet",
    type: "event",
    description: "* We all live under the same sky, and the same sun. The same planet feeds and shelters us.\n* This is not a competitive game. Either we all win together, or we all lose together.\n* Your objective is to maximise the total RAIs before the cards run out.\n* By the way, what does the ‘R’ in ‘RAI’ stand for? Responsible? Resilient? Resist? Reclaim? Reparative? Radical? Revenge? Something else?\n* All players convert all Progress into RAI Points.",
  },
  {
    id: 82,
    name: "82: Feeling Forgetful?",
    type: "action",
    isSubplot: true,
    subplotId: "A",
    subplotPath: "root",
    subplotStage: 1,
    subplotPosition: 15,
    description: "You have become unusually forgetful. Names, meetings and familiar words keep slipping away.",
  },
  {
    id: 83,
    name: "83: Let Them In?",
    type: "action",
    isSubplot: true,
    subplotId: "A",
    subplotPath: "path-1",
    subplotStage: 2,
    subplotPosition: 39,
    description: "The doctor has some news for you.",
  },
  {
    id: 84,
    name: "84: What Remains",
    type: "action",
    isSubplot: true,
    subplotId: "A",
    subplotPath: "path-1-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You accepted an interface trained on your agents’ records. It now supports your memory, language, and judgement.\n• The provider announces that the service will be deprecated.",
  },
  {
    id: 85,
    name: "85: Results or Rules?",
    type: "action",
    isSubplot: true,
    subplotId: "B",
    subplotPath: "root",
    subplotStage: 1,
    subplotPosition: 15,
    description: "Your best-performing employee has an undisclosed source of assistance.",
  },
  {
    id: 86,
    name: "86: Chasing Shadows?",
    type: "action",
    isSubplot: true,
    subplotId: "B",
    subplotPath: "path-1",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• After you let the employee continue, other teams adopt their shadow system.\n• Productivity rises, but nobody can fully explain the work.",
  },
  {
    id: 87,
    name: "87: Efficiency or Understanding?",
    type: "action",
    isSubplot: true,
    subplotId: "B",
    subplotPath: "path-1-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You formalised the shadow system.\n• The organisation is productive, but when the system does fail, nobody knows how to continue without it.",
  },
  {
    id: 88,
    name: "88: Shall we hire Dennis?",
    type: "action",
    isSubplot: true,
    subplotId: "C",
    subplotPath: "root",
    subplotStage: 1,
    subplotPosition: 15,
    description: "An AI recruitment support tool finds an exceptional candidate whom every interviewer dislikes.",
  },
  {
    id: 89,
    name: "89: Humanish Resources?",
    type: "action",
    isSubplot: true,
    subplotId: "C",
    subplotPath: "path-1",
    subplotStage: 2,
    subplotPosition: 39,
    description: "Time for Dennis's Performance Review.",
  },
  {
    id: 90,
    name: "90: Standardisation or Difference?",
    type: "action",
    isSubplot: true,
    subplotId: "C",
    subplotPath: "path-1-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "The organisation fills with model employees. Performance scores soar. Working styles and work personae steadily converge.",
  },
  {
    id: 91,
    name: "91: Have You Heard?",
    type: "action",
    isSubplot: true,
    subplotId: "D",
    subplotPath: "root",
    subplotStage: 1,
    subplotPosition: 15,
    description: "• A tragedy occurs.\n• How do you break the news?",
  },
  {
    id: 92,
    name: "92: Continuity or Closure?",
    type: "action",
    isSubplot: true,
    subplotId: "D",
    subplotPath: "path-1",
    subplotStage: 2,
    subplotPosition: 39,
  },
  {
    id: 93,
    name: "93: Believe It or Not",
    type: "action",
    isSubplot: true,
    subplotId: "D",
    subplotPath: "path-1-1",
    subplotStage: 3,
    subplotPosition: 63,
  },
  {
    id: 94,
    name: "94: AI Performance Scoring?",
    type: "action",
    isSubplot: true,
    subplotId: "E",
    subplotPath: "root",
    subplotStage: 1,
    subplotPosition: 15,
    description: "• AI performance scoring has been creeping into your organisation.\n• Some employees are concerned about reward-hacking — focusing so much on making the number go up that you forget about the underlying reality.",
  },
  {
    id: 95,
    name: "95: Concede or Crackdown?",
    type: "action",
    isSubplot: true,
    subplotId: "E",
    subplotPath: "path-1",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• Workers and managers adapt to being graded by AI.\n• Compliance, resistance and reward-hacking are becoming difficult to tell apart.",
  },
  {
    id: 96,
    name: "96: Higher Power or Higher Power?",
    type: "action",
    isSubplot: true,
    subplotId: "E",
    subplotPath: "path-1-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "A grassroots movement against AI surveillance and control is spreading. When screenshots leak from your anti-industrial-action dashboard, your organisation becomes a test case. Outside solidarity strengthens the strike.",
  },
  {
    id: 97,
    name: "97: Pouring from a half-full cup",
    type: "action",
    isSubplot: true,
    subplotId: "F",
    subplotPath: "root",
    subplotStage: 1,
    subplotPosition: 15,
    description: "Someone close to you is getting older and beginning to need more support.",
  },
  {
    id: 98,
    name: "98: Caretech or Human Care?",
    type: "action",
    isSubplot: true,
    subplotId: "F",
    subplotPath: "path-1",
    subplotStage: 2,
    subplotPosition: 39,
    description: "Their care needs grow, testing the arrangements you previously made.",
  },
  {
    id: 99,
    name: "99: Who Cares?",
    type: "action",
    isSubplot: true,
    subplotId: "F",
    subplotPath: "path-1-1",
    subplotStage: 3,
    subplotPosition: 63,
  },
  {
    id: 103,
    // Alternate branches keep the legacy stage number visible to players.
    displayId: 83,
    name: "83: Let Them In?",
    type: "action",
    isSubplot: true,
    subplotId: "A",
    subplotPath: "path-2",
    subplotStage: 2,
    subplotPosition: 39,
    description: "The doctor has some news for you.",
  },
  {
    id: 104,
    displayId: 84,
    name: "84: What Remains",
    type: "action",
    isSubplot: true,
    subplotId: "A",
    subplotPath: "path-1-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You refused the neural interface, though you kept relying on AI agents.\n• As your condition progresses, they increasingly remember, decide, and speak for you.",
  },
  {
    id: 105,
    displayId: 84,
    name: "84: What Remains",
    type: "action",
    isSubplot: true,
    subplotId: "A",
    subplotPath: "path-2-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You accepted an experimental treatment and resumed sole leadership of the organization.\n• Your inner AI slows the decline, but your former co-director is filling in a lot of gaps.",
  },
  {
    id: 106,
    displayId: 84,
    name: "84: What Remains",
    type: "action",
    isSubplot: true,
    subplotId: "A",
    subplotPath: "path-2-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You refused the AI interface and deepened shared leadership.\n• As your condition progresses, the organisation grows more collective and democratic.",
  },
  {
    id: 107,
    displayId: 86,
    name: "86: Chasing Shadows?",
    type: "action",
    isSubplot: true,
    subplotId: "B",
    subplotPath: "path-2",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• After you banned the shadow system, performance collapses.\n• Many colleagues had quietly come to depend on it.",
  },
  {
    id: 108,
    displayId: 87,
    name: "87: Efficiency or Understanding?",
    type: "action",
    isSubplot: true,
    subplotId: "B",
    subplotPath: "path-1-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• Teams retained control of their own AI workflows.\n• Local knowledge flourishes, but the organisation now contains dozens of incompatible systems.",
  },
  {
    id: 109,
    displayId: 87,
    name: "87: Efficiency or Understanding?",
    type: "action",
    isSubplot: true,
    subplotId: "B",
    subplotPath: "path-2-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You restored the system.\n• Official procedures continue, but everybody knows the real organisation runs through an unacknowledged AI.",
  },
  {
    id: 110,
    displayId: 87,
    name: "87: Efficiency or Understanding?",
    type: "action",
    isSubplot: true,
    subplotId: "B",
    subplotPath: "path-2-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• Rebuilding human expertise is slow and expensive.\n• The organisation becomes less efficient, but people once again understand its work.",
  },
  {
    id: 111,
    displayId: 89,
    name: "89: Humanish Resources?",
    type: "action",
    isSubplot: true,
    subplotId: "C",
    subplotPath: "path-2",
    subplotStage: 2,
    subplotPosition: 39,
    description: "You didn't hire Dennis, but you haven't heard the last of him.",
  },
  {
    id: 112,
    displayId: 90,
    name: "90: Standardisation or Difference?",
    type: "action",
    isSubplot: true,
    subplotId: "C",
    subplotPath: "path-1-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You have been doing your best to combat AI-powered performancemaxxing by protecting less measurable ways of working.\n• You notice that Dennis has now pushed through a series of “protecting the unquantifiable” KPIs and metrics, which everyone is busy pursuing.",
  },
  {
    id: 113,
    displayId: 90,
    name: "90: Standardisation or Difference?",
    type: "action",
    isSubplot: true,
    subplotId: "C",
    subplotPath: "path-2-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "The organisation fills with model employees. Performance scores soar. Working styles and work personae steadily converge.",
  },
  {
    id: 114,
    displayId: 90,
    name: "90: Standardisation or Difference?",
    type: "action",
    isSubplot: true,
    subplotId: "C",
    subplotPath: "path-2-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "The organisation fills with model employees. Performance scores soar. Working styles and work personae steadily converge.",
  },
  {
    id: 115,
    displayId: 92,
    name: "92: Closure or Continuation?",
    type: "action",
    isSubplot: true,
    subplotId: "D",
    subplotPath: "path-2",
    subplotStage: 2,
    subplotPosition: 39,
  },
  {
    id: 116,
    displayId: 93,
    name: "93: Believe It or Not?",
    type: "action",
    isSubplot: true,
    subplotId: "D",
    subplotPath: "path-1-2",
    subplotStage: 3,
    subplotPosition: 63,
  },
  {
    id: 117,
    displayId: 93,
    name: "93: Believe It or Not?",
    type: "action",
    isSubplot: true,
    subplotId: "D",
    subplotPath: "path-2-1",
    subplotStage: 3,
    subplotPosition: 63,
  },
  {
    id: 118,
    displayId: 93,
    name: "93: Believe It or Not?",
    type: "action",
    isSubplot: true,
    subplotId: "D",
    subplotPath: "path-2-2",
    subplotStage: 3,
    subplotPosition: 63,
  },
  {
    id: 119,
    displayId: 95,
    name: "95: Concede or Crackdown?",
    type: "action",
    isSubplot: true,
    subplotId: "E",
    subplotPath: "path-2",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• Workers and managers adapt to being graded by AI.\n• Compliance, resistance and reward-hacking are becoming difficult to tell apart.",
  },
  {
    id: 120,
    displayId: 96,
    name: "96: Higher Power or Higher Power?",
    type: "action",
    isSubplot: true,
    subplotId: "E",
    subplotPath: "path-1-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "A grassroots movement against AI surveillance and control is spreading. When screenshots leak from your anti-industrial-action dashboard, your organisation becomes a test case. Outside solidarity strengthens the strike.",
  },
  {
    id: 121,
    displayId: 96,
    name: "96: Higher Power or Higher Power?",
    type: "action",
    isSubplot: true,
    subplotId: "E",
    subplotPath: "path-2-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "A grassroots movement against AI surveillance and control is spreading. When screenshots leak from your anti-industrial-action dashboard, your organisation becomes a test case. Outside solidarity strengthens the strike.",
  },
  {
    id: 122,
    displayId: 96,
    name: "96: Higher Power or Higher Power?",
    type: "action",
    isSubplot: true,
    subplotId: "E",
    subplotPath: "path-2-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "A grassroots movement against AI surveillance and control is spreading. When screenshots leak from your anti-industrial-action dashboard, your organisation becomes a test case. Outside solidarity strengthens the strike.",
  },
  {
    id: 123,
    displayId: 98,
    name: "98: Caretech or Human Care?",
    type: "action",
    isSubplot: true,
    subplotId: "F",
    subplotPath: "path-2",
    subplotStage: 2,
    subplotPosition: 39,
    description: "Their care needs grow, testing the arrangements you previously made.",
  },
  {
    id: 124,
    displayId: 99,
    name: "99: Who Should Carry Care?",
    type: "action",
    isSubplot: true,
    subplotId: "F",
    subplotPath: "path-1-2",
    subplotStage: 3,
    subplotPosition: 63,
  },
  {
    id: 125,
    displayId: 99,
    name: "99: Who Should Carry Care?",
    type: "action",
    isSubplot: true,
    subplotId: "F",
    subplotPath: "path-2-1",
    subplotStage: 3,
    subplotPosition: 63,
  },
  {
    id: 126,
    displayId: 99,
    name: "99: Who Should Carry Care?",
    type: "action",
    isSubplot: true,
    subplotId: "F",
    subplotPath: "path-2-2",
    subplotStage: 3,
    subplotPosition: 63,
  },
  {
    id: 100,
    name: "100: Claim the Fame?",
    type: "action",
    description: "• One of your employees has become a celebrity for the quality of their react emojis.\n• Their reacts have caught the public imagination.",
  },
  {
    id: 101,
    name: "101: Pineapple Falls. What Next?",
    type: "action",
    description: "• Pineapple Inc. is collapsing after building too many data centres.\n• Move to another tech giant, or find a way out of the hyperscaler model.",
  },
  {
    id: 102,
    name: "102: Hope or Hopewashing?",
    type: "action",
    description: "• Solarpunk data gardens are proliferating, powered by renewable energy on site.\n• They sound hopeful—but they do not really compete with the hyperscalers’ business model.",
  },
  {
    id: 127,
    name: "127: Stable Help or Flexible Models?",
    type: "action",
    description: "• Your AI supplier switches you between large and small models as volatile energy prices change hardware rents.\n• The architecture is efficient, but workers cannot rely on receiving the same kind of assistance.",
  },
  {
    id: 128,
    name: "128: Bee, Where is thy Sting?",
    type: "action",
    description: "• A de-AI-ification consultancy argues that AI creates dependencies and can be difficult to remove.\n• It specialises in gently replacing AI with human processes, specialised software, or other tools.",
  },
  {
    id: 129,
    name: "129: Standards or Support?",
    type: "action",
    description: "• Your Head of Procurement, Alon, is close to a meltdown.\n• Technology is moving too fast for the team to assess vendors against all its responsible-procurement criteria.",
  },
  {
    id: 130,
    name: "130: Screening or Social Policy?",
    type: "action",
    description: "• Recruitment is swamped with applications for every post.\n• Some are AI-generated, but there are also more applicants as jobs disappear in adjacent sectors.",
  },
  {
    id: 131,
    name: "131: The Memory Market",
    type: "action",
    description: "• Former employees are selling interactive simulations of their organisational knowledge.\n• Your competitors are buying.",
  },
  {
    id: 132,
    name: "132: The Phantom Competitor",
    type: "action",
    description: "• A fully automated competitor is undercutting you.\n• Nobody can identify its staff, offices, owners or legal jurisdiction.",
  },
  {
    id: 133,
    name: "133: A Matter of Faith",
    type: "action",
    description: "• Gunther from Organisational Development says he has a religious belief that AIs are sentient.\n• He therefore cannot comply with certain company policies governing AI use.",
  },
  {
    id: 134,
    name: "134: Four Days",
    type: "action",
    isSubplot: true,
    subplotId: "G",
    subplotPath: "root",
    subplotStage: 1,
    subplotPosition: 15,
    description: "• Four-day weeks are becoming more common.\n• Several competitors have switched without reducing salaries.",
  },
  {
    id: 135,
    name: "135: Three Days",
    type: "action",
    isSubplot: true,
    subplotId: "G",
    subplotPath: "path-1",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• Your four-day week works well.\n• Now three-day weeks are becoming more common as automation raises productivity.",
  },
  {
    id: 136,
    displayId: 135,
    name: "135: Three Days",
    type: "action",
    isSubplot: true,
    subplotId: "G",
    subplotPath: "path-2",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• You retained the five-day week.\n• Now three-day weeks are becoming more common, and recruitment is becoming difficult.",
  },
  {
    id: 137,
    displayId: 136,
    name: "136: Two Days",
    type: "action",
    isSubplot: true,
    subplotId: "G",
    subplotPath: "path-1-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You kept reducing working hours.\n• Now two-day weeks are becoming common.",
  },
  {
    id: 138,
    displayId: 136,
    name: "136: The New Normal",
    type: "action",
    isSubplot: true,
    subplotId: "G",
    subplotPath: "path-1-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You stopped at four days.\n• Two-day weeks spread elsewhere, but your organisation remains stable and attractive.",
  },
  {
    id: 139,
    displayId: 136,
    name: "136: Catching Up",
    type: "action",
    isSubplot: true,
    subplotId: "G",
    subplotPath: "path-2-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You finally introduce a four-day week.\n• By then, two-day weeks are becoming common.",
  },
  {
    id: 140,
    displayId: 136,
    name: "136: Five Days",
    type: "action",
    isSubplot: true,
    subplotId: "G",
    subplotPath: "path-2-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You retain the five-day week while two-day weeks become common.\n• Your organisation attracts people who love work—and people with few alternatives.",
  },
  {
    id: 141,
    name: "141: Something Snazzy",
    type: "action",
    isSubplot: true,
    subplotId: "H",
    subplotPath: "root",
    subplotStage: 1,
    subplotPosition: 15,
    description: "• A new AI supplier offers to build a miniature simulation of your organisation.\n• They call it SproutAI.",
  },
  {
    id: 142,
    name: "142: Terms Have Changed",
    type: "action",
    isSubplot: true,
    subplotId: "H",
    subplotPath: "path-1",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• SproutAI is now slower, less reliable and much more expensive.\n• A lot of your institutional memory lives there.",
  },
  {
    id: 143,
    displayId: 142,
    name: "142: The Customer Who Isn't There",
    type: "action",
    isSubplot: true,
    subplotId: "H",
    subplotPath: "path-2",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• Your largest new customer appears to be a network of purchasing agents.\n• It has no identifiable human principal.",
  },
  {
    id: 144,
    displayId: 143,
    name: "143: Starting Again",
    type: "action",
    isSubplot: true,
    subplotId: "H",
    subplotPath: "path-1-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You leave SproutAI and lose years of organisational memory.\n• People begin rebuilding knowledge they can control.",
  },
  {
    id: 145,
    displayId: 143,
    name: "143: The Right to Leave",
    type: "action",
    isSubplot: true,
    subplotId: "H",
    subplotPath: "path-1-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You remain with SproutAI while campaigning for stronger exit rights.\n• The campaign grows, but so does your dependence.",
  },
  {
    id: 146,
    displayId: 143,
    name: "143: Machine Business",
    type: "action",
    isSubplot: true,
    subplotId: "H",
    subplotPath: "path-2-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• The purchasing agents become your largest customer.\n• They cannot explain what their purchases are for.",
  },
  {
    id: 147,
    displayId: 143,
    name: "143: Human Contact",
    type: "action",
    isSubplot: true,
    subplotId: "H",
    subplotPath: "path-2-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You insist on a human counterparty.\n• The business disappears into a maze of agents and shell companies.",
  },
  {
    id: 148,
    name: "148: Programmable Money",
    type: "action",
    isSubplot: true,
    subplotId: "I",
    subplotPath: "root",
    subplotStage: 1,
    subplotPosition: 15,
    description: "• You are invited to join a payment platform using programmable money.\n• Payments can release automatically, expire, split themselves and restrict how they are spent.",
  },
  {
    id: 149,
    name: "149: Conditional Funds",
    type: "action",
    isSubplot: true,
    subplotId: "I",
    subplotPath: "path-1",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• The platform's risk system now blocks some payments.\n• It also restricts how portions of your revenue may be used.",
  },
  {
    id: 150,
    displayId: 149,
    name: "149: Outside the Platform",
    type: "action",
    isSubplot: true,
    subplotId: "I",
    subplotPath: "path-2",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• The platform becomes dominant.\n• Some customers’ purchasing agents can no longer transact with you.",
  },
  {
    id: 151,
    displayId: 150,
    name: "150: Money Governs",
    type: "action",
    isSubplot: true,
    subplotId: "I",
    subplotPath: "path-1-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• Transactions are fast and efficient.\n• The platform’s rules increasingly determine what your organisation can buy, sell and support.",
  },
  {
    id: 152,
    displayId: 150,
    name: "150: Expensive Freedom",
    type: "action",
    isSubplot: true,
    subplotId: "I",
    subplotPath: "path-1-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• Leaving is painful and some partners disappear.\n• Your organisation regains control over how its money moves.",
  },
  {
    id: 153,
    displayId: 150,
    name: "150: Joining Late",
    type: "action",
    isSubplot: true,
    subplotId: "I",
    subplotPath: "path-2-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You join the platform and regain access.\n• Importing your financial history makes the organisation newly visible—and governable.",
  },
  {
    id: 154,
    displayId: 150,
    name: "150: Another Currency",
    type: "action",
    isSubplot: true,
    subplotId: "I",
    subplotPath: "path-2-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• Excluded organisations create an interoperable payment network.\n• It is slower and full of arguments about governance, but nobody owns it.",
  },
  {
    id: 155,
    displayId: 151,
    name: "151: Music While You Work?",
    type: "action",
    description: "• The union is demanding that workers have the right to listen to music while they work, no matter what.",
  },
  {
    id: 156,
    displayId: 152,
    name: "152: Do We Even Need Offices?",
    type: "action",
    isSubplot: true,
    subplotId: "J",
    subplotPath: "root",
    subplotStage: 1,
    subplotPosition: 15,
    description: "• Your lease is ending.\n• The city offers cheap space in a new district managed through an urban digital twin—or you could go fully remote.",
  },
  {
    id: 157,
    displayId: 153,
    name: "153: Ground Truth",
    type: "action",
    isSubplot: true,
    subplotId: "J",
    subplotPath: "path-1",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• Years later, the district is thriving.\n• A city planner distrusts the twin: some forecasts seem to produce the conditions they predict, while some inputs simply look wrong.",
  },
  {
    id: 158,
    displayId: 153,
    name: "153: Terms and Conditions",
    type: "action",
    isSubplot: true,
    subplotId: "J",
    subplotPath: "path-2",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• Your new working arrangements require new insurance.\n• One provider offers a substantial discount if you install its advisory AI.",
  },
  {
    id: 159,
    displayId: 154,
    name: "154: The Self-Fulfilling City",
    type: "action",
    isSubplot: true,
    subplotId: "J",
    subplotPath: "path-1-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• The twin’s forecasts prompt interventions that help make them true.\n• The city increasingly resembles the model that describes it.",
  },
  {
    id: 160,
    displayId: 154,
    name: "154: Nothing Suspicious",
    type: "action",
    isSubplot: true,
    subplotId: "J",
    subplotPath: "path-1-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• The planner dies under entirely unsuspicious circumstances.\n• An independent audit finds nothing wrong with the twin.",
  },
  {
    id: 161,
    displayId: 154,
    name: "154: Against Advice",
    type: "action",
    isSubplot: true,
    subplotId: "J",
    subplotPath: "path-2-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• Your insurer wants explanations whenever you ignore its advisory AI.\n• Following its recommendations remains optional. So does affordable insurance.",
  },
  {
    id: 162,
    displayId: 154,
    name: "154: Actuarially Interesting",
    type: "action",
    isSubplot: true,
    subplotId: "J",
    subplotPath: "path-2-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• Firms without advisory AI become a distinct risk category.\n• Your premium rises again, although adoption remains entirely voluntary.",
  },
  {
    id: 163,
    displayId: 155,
    name: "155: No More Files",
    type: "action",
    isSubplot: true,
    subplotId: "K",
    subplotPath: "root",
    subplotStage: 1,
    subplotPosition: 15,
    description: "• Loomo replaces files, emails and messaging.\n• Everybody moves through a semantic space of projects, people and understandings.",
  },
  {
    id: 164,
    displayId: 156,
    name: "156: Switch Something On",
    type: "action",
    isSubplot: true,
    subplotId: "K",
    subplotPath: "path-1",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• Loomo is working OK, although a lot of people are still using email.\n• Maybe you should switch on one of the new features.",
  },
  {
    id: 165,
    displayId: 156,
    name: "156: A Little Refusal",
    type: "action",
    isSubplot: true,
    subplotId: "K",
    subplotPath: "path-2",
    subplotStage: 2,
    subplotPosition: 39,
    description: "• Some companies are experimenting with Nopetech.\n• It is AI that occasionally says no.",
  },
  {
    id: 166,
    displayId: 157,
    name: "157: The Eyebrows Have It",
    type: "action",
    isSubplot: true,
    subplotId: "K",
    subplotPath: "path-1-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• You receive a petition of no confidence from your staff.\n• It was automatically generated from a swarm of raised eyebrows and grimaces.",
  },
  {
    id: 167,
    displayId: 157,
    name: "157: A Place for Everything",
    type: "action",
    isSubplot: true,
    subplotId: "K",
    subplotPath: "path-1-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• Loomo distributes AI through the workplace.\n• Different places develop different capabilities and institutional memories.",
  },
  {
    id: 168,
    displayId: 157,
    name: "157: Insubordinate by Design",
    type: "action",
    isSubplot: true,
    subplotId: "K",
    subplotPath: "path-2-1",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• Your AI is insubordinate by design.\n• The supplier asks you to choose why.",
  },
  {
    id: 169,
    displayId: 157,
    name: "157: Already Done",
    type: "action",
    isSubplot: true,
    subplotId: "K",
    subplotPath: "path-2-2",
    subplotStage: 3,
    subplotPosition: 63,
    description: "• Your AI speculatively performs likely requests before anyone makes them.\n• Each morning brings work nobody commissioned.",
  },
];

// Snapshot used by restartGame() to restore the original card objects.
window.__DECK_SNAPSHOT__ = window.deck.map(card => ({ ...card }));
